from __future__ import annotations

from typing import Protocol

from pydantic import BaseModel, Field

from ai_engine.modeling.contracts import InferenceContext, ModelFeatureAttribution, ModelOutput
from ai_engine.modeling.evidence_adapter import ModelEvidencePayload
from ai_engine.schemas.enums import DataQualityLevel, DriftStatus, FeatureDirection, SignalTrend


class ModelInput(BaseModel):
    features: dict[str, float | int | str | bool | None] = Field(
        ...,
        description="Feature values prepared for model inference.",
    )
    metadata: dict[str, str] = Field(
        default_factory=dict,
        description="Model inference metadata such as asset, machine, or feature-set identifiers.",
    )


class ModelFeatureContribution(ModelFeatureAttribution):
    """Backward-compatible alias used by the runtime layer."""


class ModelPrediction(ModelOutput):
    """Structured output contract returned by a model runtime."""

    def to_evidence_payload(self) -> ModelEvidencePayload:
        return ModelEvidencePayload.model_validate(self.model_dump(mode="json"))


class ModelRuntime(Protocol):
    def predict(self, model_input: ModelInput) -> ModelPrediction:
        ...


class MockModelRuntime:
    def predict(self, model_input: ModelInput) -> ModelPrediction:
        vibration = float(model_input.features.get("vibration_rms", 0.0) or 0.0)
        temperature = float(model_input.features.get("temperature_mean", 0.0) or 0.0)

        anomaly_score = min(1.0, (vibration / 10.0) * 0.6 + (temperature / 100.0) * 0.4)
        health_score = max(0.0, 1.0 - anomaly_score)
        failure_probability = min(1.0, anomaly_score * 0.85)
        rul_estimate_hours = max(0.0, 500.0 * (1.0 - failure_probability))

        return ModelPrediction(
            health_score=health_score,
            anomaly_score=anomaly_score,
            failure_horizon_probability=failure_probability,
            rul_estimate_hours=rul_estimate_hours,
            prediction_confidence=0.75,
            signal_quality_score=0.90,
            data_completeness_score=0.95,
            drift_score=0.10,
            recent_signal_trend=SignalTrend.DEGRADING if anomaly_score >= 0.5 else SignalTrend.STABLE,
            data_quality_status=DataQualityLevel.OK,
            drift_status=DriftStatus.NONE,
            top_feature_attributions=[
                ModelFeatureContribution(
                    feature_name="vibration_rms",
                    importance=0.60,
                    direction=FeatureDirection.INCREASE_RISK,
                ),
                ModelFeatureContribution(
                    feature_name="temperature_mean",
                    importance=0.40,
                    direction=FeatureDirection.INCREASE_RISK,
                ),
            ],
            evidence_notes=["Generated by MockModelRuntime."],
            inference_context=InferenceContext(
                horizon_hours=72.0,
                model_name="mock_runtime",
                model_version="mock-v1",
                feature_set_version=model_input.metadata.get("feature_set_version"),
                inference_notes=["Synthetic prediction for local testing."],
            ),
        )
