from __future__ import annotations

from typing import Protocol

from pydantic import BaseModel, Field

from ai_engine.modeling.evidence_adapter import ModelEvidencePayload
from ai_engine.schemas.enums import DataQualityLevel, DriftStatus, FeatureDirection, SignalTrend


class ModelInput(BaseModel):
    features: dict[str, float | int | str | bool | None] = Field(
        ...,
        description="Feature values prepared for model inference.",
    )
    metadata: dict[str, str] = Field(
        default_factory=dict,
        description="Model inference metadata such as asset, machine, or feature-set identifiers.",
    )


class ModelFeatureContribution(BaseModel):
    feature_name: str = Field(..., description="Name of the feature contributing to the prediction.")
    importance: float = Field(..., description="Relative feature contribution score.")
    direction: FeatureDirection = Field(..., description="Direction of feature contribution to risk.")


class ModelPrediction(BaseModel):
    health_score: float | None = Field(None, ge=0.0, le=1.0, description="Predicted health score.")
    anomaly_score: float | None = Field(None, ge=0.0, le=1.0, description="Predicted anomaly score.")
    failure_horizon_probability: float | None = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Predicted probability of failure within the configured horizon.",
    )
    rul_estimate_hours: float | None = Field(None, ge=0.0, description="Predicted remaining useful life in hours.")
    prediction_confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score for the prediction.")
    signal_quality_score: float = Field(..., ge=0.0, le=1.0, description="Quality score of input signal data.")
    data_completeness_score: float = Field(..., ge=0.0, le=1.0, description="Completeness score of model inputs.")
    drift_score: float | None = Field(None, ge=0.0, le=1.0, description="Optional distribution drift score.")
    recent_signal_trend: SignalTrend = Field(..., description="Recent trend inferred from input signals.")
    data_quality_status: DataQualityLevel = Field(..., description="Quality status assigned to model inputs.")
    drift_status: DriftStatus = Field(..., description="Drift status assigned to current inputs.")
    top_feature_attributions: list[ModelFeatureContribution] = Field(
        default_factory=list,
        description="Top feature contributions from the model.",
    )
    evidence_notes: list[str] = Field(default_factory=list, description="Notes about the model prediction.")

    def to_evidence_payload(self) -> ModelEvidencePayload:
        return ModelEvidencePayload.model_validate(self.model_dump(mode="json"))


class ModelRuntime(Protocol):
    def predict(self, model_input: ModelInput) -> ModelPrediction:
        ...


class MockModelRuntime:
    def predict(self, model_input: ModelInput) -> ModelPrediction:
        vibration = float(model_input.features.get("vibration_rms", 0.0) or 0.0)
        temperature = float(model_input.features.get("temperature_mean", 0.0) or 0.0)

        anomaly_score = min(1.0, (vibration / 10.0) * 0.6 + (temperature / 100.0) * 0.4)
        health_score = max(0.0, 1.0 - anomaly_score)
        failure_probability = min(1.0, anomaly_score * 0.85)
        rul_estimate_hours = max(0.0, 500.0 * (1.0 - failure_probability))

        return ModelPrediction(
            health_score=health_score,
            anomaly_score=anomaly_score,
            failure_horizon_probability=failure_probability,
            rul_estimate_hours=rul_estimate_hours,
            prediction_confidence=0.75,
            signal_quality_score=0.90,
            data_completeness_score=0.95,
            drift_score=0.10,
            recent_signal_trend=SignalTrend.DEGRADING if anomaly_score >= 0.5 else SignalTrend.STABLE,
            data_quality_status=DataQualityLevel.OK,
            drift_status=DriftStatus.NONE,
            top_feature_attributions=[
                ModelFeatureContribution(
                    feature_name="vibration_rms",
                    importance=0.60,
                    direction=FeatureDirection.INCREASE_RISK,
                ),
                ModelFeatureContribution(
                    feature_name="temperature_mean",
                    importance=0.40,
                    direction=FeatureDirection.INCREASE_RISK,
                ),
            ],
            evidence_notes=["Generated by MockModelRuntime."],
        )
